model_type: gnn-transformer

gnn_type: gcn
gnn_virtual_node: false

graph_pooling: cls

lr: 0.0008

seed: 1234

transformer_norm_input: true

epochs: 20

d_model: 128
dim_feedforward: 128
num_encoder_layers: 2
scheduler: cosine

transformer_dropout: 0.2
gnn_dropout: 0.2
gnn_emb_dim: 128